### ISSUE TITLE
Optimization API

### ISSUE THREAD

**Issue by jill-cardamon** [mapbox/mapbox-directions-swift#625] opened 2021-11-02 12:53 UTC
This library should be able to make requests to and handle responses from the [Optimization API](https://docs.mapbox.com/api/navigation/optimization/).

/cc @mapbox/navigation-ios

**Comment by S2Ler** [comment] 2021-11-26 10:33
Duplicate of #107

**Closed by S2Ler** 2021-11-26 10:33 UTC
Labels: improvement, platform parity, optimization
